[package]
name = "democrachain"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[dependencies]
soroban-sdk.workspace = true
